### ISSUE TITLE
Live weather reports about the place you search

### ISSUE THREAD

**Issue by AbhishekKumar2002** [biratdatta/Webpage-Maker#109]
Hi @biratdatta  I want to make a web page that give you live weather reports about the place you search. Kindly assign me this issue for Hacktoberfest 2022.

**Comment by AbhishekKumar2002** [comment]
I will use Simple HTML, CSS, and JS.

**Comment by biratdatta** [comment]
Go ahead @AbhishekKumar2002

**Comment by AbhishekKumar2002** [comment]
Kindly check the weather Page and accept my PR.

**Comment by AbhishekKumar2002** [comment]
Thank You for giving me this wonderful opportunity @biratdatta
