### ISSUE TITLE
snapchat icon is missing

### ISSUE THREAD

**Issue by Shahin2003** [biratdatta/Webpage-Maker#128]
Please assign it to me.

**Comment by Shahin2003** [comment]
@biratdatta and I would also like to enter the proper placeholder values in "contact us" section.

**Comment by biratdatta** [comment]
Sure go ahead

**Comment by Jiya-garg9971** [comment]
please assign it to me

**Comment by Shahin2003** [comment]
@biratdatta @Jiya-garg9971  i fixed the issue already.
