### ISSUE TITLE
Rearranging all the files and put it into a structure

### ISSUE THREAD

**Issue by biratdatta** [biratdatta/Webpage-Maker#139]
Anyone can take their time out and put all the files in named manner and make it more visually appealing and more accessible to people.

**Comment by Swap-nil-2003** [comment]
I would like to work on this @biratdatta. One quick question: Do you basically want the files to be put into the respective folders in the repo?

**Comment by biratdatta** [comment]
Yeah that's what I wanted @Swap-nil-2003

**Comment by Kritika30032002** [comment]
May I also contribute to this?

**Comment by biratdatta** [comment]
@Swap-nil-2003 what is the status?

**Comment by Swap-nil-2003** [comment]
@biratdatta I have raised the PR in #145
