### ISSUE TITLE
Adding use state and use effect for react js cheatsheet 

### ISSUE THREAD

**Issue by yat2k** [biratdatta/Webpage-Maker#158]
I want to add some basics of using use state and use effect in react

**Comment by biratdatta** [comment]
Sure go ahead

**Comment by yat2k** [comment]
Someone else already updated it, so i added the useContext hook. 
Also, i must mention that the previous contributor who added useState and useEffect blatantly copied the docs without even remembering that they were supposed to shorten it for making it a cheatsheet xD
