### ISSUE TITLE
Adding Grid Layout file

### ISSUE THREAD

**Issue by Kritika30032002** [biratdatta/Webpage-Maker#162]
Adding a file explaining the concept of grid layout.

Assign this issue to me!!

**Comment by biratdatta** [comment]
Sure

**Comment by Kritika30032002** [comment]
Hey !! 
Is this possible to create different PR's for different commits as When I commited for the another issue of your project only , it got commit in the same PR?

But I need to make it under Different PR's as they are 2 different issues.
