### ISSUE TITLE
CSS card toggle animation

### ISSUE THREAD

**Issue by Ritu-2001** [biratdatta/Webpage-Maker#166]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ritu-2001** [comment]
will please assign me ??

**Comment by biratdatta** [comment]
Cool go ahead

**Comment by Ritu-2001** [comment]
@biratdatta  do it , please go and check it
