### ISSUE TITLE
Adding Navbar designs

### ISSUE THREAD

**Issue by shriya-tiwari** [biratdatta/Webpage-Maker#28]
I can write HTML, CSS for different navbar designs.

**Comment by shriya-tiwari** [comment]
> I can write HTML, CSS for different navbar designs.

Please assign it to me.

**Comment by biratdatta** [comment]
@shriya-tiwari  pls do it

**Comment by shriya-tiwari** [comment]
> @shriya-tiwari pls do it

yup on it !!

**Comment by TenzinNsut** [comment]
Hey Birat Datta, I am new to opensource and would like to contribute to your project, specifically in Navigation Bar design. 
I have some past experience in creating web pages. So, if possible I would really love to work for the same.

**Comment by shriya-tiwari** [comment]
> @TenzinNsut I can assign you until @shriya-tiwari wants to un-assign from it or after a specific period of time

I am currently working on this one, and will shortly put a PR regarding this.

**Comment by sumitbaroniya** [comment]
Please assign me this issue

**Comment by itsmeHrishi** [comment]
I want to start my open-source contribution journey, I will add more variety of navbars. I will be thankful to you if you assign it to me.

**Comment by biratdatta** [comment]
@shriya-tiwari updates
