### ISSUE TITLE
discovered a typo in index.html file on the root directory

### ISSUE THREAD

**Issue by Emilance** [biratdatta/Webpage-Maker#30]
Commented line 160 in the index.html file of the root directory was typed  wrongly -[ Lets give it a id name so we can access its value using getElementbyId] instead of [Lets give it an id name so we can access its value using getElementbyId ].

A wrong article was assigned to id it should be 'an id' not 'a id'

**Comment by Johnoris** [comment]
Assign this to me I'll love to fix it

**Comment by Johnoris** [comment]
I already fixed and created a pr you can close the issue
