### ISSUE TITLE
Improve UI of the page

### ISSUE THREAD

**Issue by Anjuli08** [biratdatta/Webpage-Maker#51]
I would like to improve the UI of the page through css under hactoberfest.

**Comment by biratdatta** [comment]
sure

**Comment by BhaveshAnandpara** [comment]
I would like to contribute , Can I ??

**Comment by biratdatta** [comment]
Sure

**Comment by Anjuli08** [comment]
> Sure

Hey I'm still working on it

**Comment by BhaveshAnandpara** [comment]
@Anjuli08 no problem 👍 You can do it as well
