### ISSUE TITLE
Git cheat sheet

### ISSUE THREAD

**Issue by Mahich123** [biratdatta/Webpage-Maker#59]
I would like to include git cheat sheet in this repo . Can you assign me ?

**Comment by biratdatta** [comment]
Sure you can go ahead

**Comment by Mahich123** [comment]
Should I create md file in a directory and include in their ?

**Comment by Mahich123** [comment]
Made pr can you check it pls

**Comment by sumitbaroniya** [comment]
Please assign me this issue

**Comment by sanvi0071** [comment]
Hey...I want to work for this issue kindly assign me the issue.
