### ISSUE TITLE
Mongo DB cheatsheet

### ISSUE THREAD

**Issue by aritroo** [biratdatta/Webpage-Maker#60]
Hello @biratdatta 
I want to add a Mongo DB cheat sheet . Please assign me for hacktoberfest. 

Thank You. 😀

**Comment by biratdatta** [comment]
Hey, you can create a seperate Page for that and start doing that.

**Comment by aritroo** [comment]
> Hey, you can create a seperate Page for that and start doing that.

 are u asking to add the file by creating a new directory??

**Comment by biratdatta** [comment]
No in the same thing with different extension for that

**Comment by aritroo** [comment]
> No in the same thing with different extension for that
> 

Ok got it 🙂

**Comment by sumitbaroniya** [comment]
please assign me this issue. I want to contribute in it.

**Comment by biratdatta** [comment]
Update @aritroo

**Comment by aritroo** [comment]
> Update @aritroo 

@biratdatta Sorry actually due to some technical issues I am currently unable to work on my laptop but I will fix it and will update ASAP.

**Comment by aritroo** [comment]
> Update @aritroo
@biratdatta 
due some technical problems in my laptop i couldn't able to work . I am extremely sorry for this.

**Comment by biratdatta** [comment]
Then @sumitbaroniya you can go ahead
